### ISSUE TITLE
How fix ?

### ISSUE THREAD

**Issue by hurtisvagler** [0xKayala/JaelesFuzzer#1]
Hi, my scan fails.
What could be the reason and how to fix it?
Thank you!

Running Jaeles on collected URLs
Jaeles beta v0.17.1 by @j3ssiejjj
/usr/bin/jf: line 127: 423896 Done                    httpx -silent -mc 200,301,302,403 -l "$temp_file"
     423897 Killed                  | jaeles scan -c 50 -s "$home_dir/jaeles-signatures/fuzz/common"
Scan is completed - Happy Hunting
![Screenshot_778](https://github.com/0xKayala/JaelesFuzzer/assets/120396123/a420e50d-26c7-49ef-8443-0d4422af7388)

**Comment by 0xKayala** [comment]
I am still working on this tool. It is just a prototype
